name: 'Terraform'
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.8.5"

    - name: Terraform Init
      env:
       TOKEN: ${{ secrets.YC_TOKEN }}
       CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
       FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
       TT: ${{ env.TEST }}
       TT2: ${{ TEST }}
       TT1: dfdssdfs
      shell: bash
      run: |
           echo "$AWS_ACCESS_KEY_ID"
           echo "$TT"
           echo  ${{ env.TOKEN }}
           echo  ${{ env.TEST }}
           terraform -chdir=./terraform init -backend-config="access_key=$AWS_ACCESS_KEY_ID" -backend-config="secret_key=${{ secrets.AWS_SECRET_KEY }}"
      #run: terraform -chdir=./terraform init

    - name: Terraform Format and Validate
      run: terraform -chdir=./terraform validate

    - name: Terraform Plan
      run: |
        terraform -chdir=./terraform plan -input=false -out=tfplan \
        -var="token=${{ secrets.YC_TOKEN }}" \
        -var="cloud_id=${{ secrets.YC_CLOUD_ID }}" \
        -var="folder_id=${{ secrets.YC_FOLDER_ID }}" \

    - name: Terraform Apply (Automatic Trigger)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: terraform -chdir=./terraform apply -input=false tfplan

